title:               Miao Yang
url:                 https://miaoyang129.github.io
baseurl:             ""

markdown:            kramdown
highlighter:         rouge

exclude:             ['*.sublime-*', 'README.md', 'LICENSE', 'Gemfile', 'Gemfile.lock', 'vendor/bundle']

permalink:           pretty

# Blog pagination
paginate:            5
paginate_path:       /blog/:num

# Docs pagination
docs_paginate:       5
docs_paginate_path:  /docs/page:num

blog:
  truncated_preview: false

sass:
  sass_dir:          _sass
  style:             "compressed"

author:
  name:              Miao Yang
  url:               miaoyang129.github.io
  email:             miaoyang129@gmail.com

plugins:
  - jekyll-coffeescript
  - jekyll-paginate
  - jekyll-gist
  - jekyll-paginate-v2